version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gameday"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19lrltt205u4e"
s3_prefix = "gameday"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UserEmail=\"foo@bar.baz\" AllowedCallbacks=\"http://localhost\" AuthDomainParam=\"example\" StackTagName=\"gameday\" EnvironmentTagName=\"dev\""
image_repositories = []
